modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="dmzevo_mod"
version="1.0.0"
displayName="DMZEvolutionMod"
description='''Core mod para DMZ Evolution, Añade bastantes cosas.'''
authors="InmortalPx"

[[dependencies.dmzevo_mod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dmzevo_mod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
